"""
Quick, defensive EDA for Gridlock Hackathon 2.0 Round 2 datasets (PS1 & PS2).
Grounds the strategy report in real numbers. Writes 00_data_profile.md.
Run: python profile_data.py
"""
from __future__ import annotations
import json
import os
import sys
from collections import Counter

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROUND2 = os.path.dirname(HERE)
PS1 = os.path.join(ROUND2, "PS1", "jan to may police violation_anonymized791b166.csv")
PS2 = os.path.join(ROUND2, "PS2", "Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv")
OUT = os.path.join(HERE, "00_data_profile.md")

lines: list[str] = []


def w(s: str = "") -> None:
    lines.append(s)
    print(s)


def parse_list(val):
    """violation_type / offence_code are JSON-ish list strings."""
    if not isinstance(val, str) or val.strip() in ("", "NULL", "[]"):
        return []
    try:
        out = json.loads(val)
        return out if isinstance(out, list) else [out]
    except Exception:
        return [val]


def to_dt(series):
    return pd.to_datetime(series, errors="coerce", utc=True)


def null_rate(series) -> float:
    s = series.astype("string")
    n = len(series)
    if n == 0:
        return 0.0
    miss = s.isna() | s.str.upper().isin(["NULL", "NONE", ""])
    return round(100.0 * miss.sum() / n, 1)


# ----------------------------------------------------------------------------
w("# Gridlock 2.0 Round 2 - Dataset Profile (auto-generated)\n")
w(f"_Generated by profile_data.py. Python {sys.version.split()[0]}, pandas {pd.__version__}._\n")

# ============================ PS1 ===========================================
w("\n## PS1 - Parking-Induced Congestion dataset\n")
try:
    df = pd.read_csv(PS1, dtype=str, keep_default_na=False, low_memory=False)
    n = len(df)
    w(f"- **Rows:** {n:,}  |  **Columns:** {df.shape[1]}")
    w(f"- **Columns:** {', '.join(df.columns)}")

    # Time span
    cdt = to_dt(df["created_datetime"])
    w(f"- **Time span (created):** {cdt.min()}  ->  {cdt.max()}")

    # Violation types (exploded)
    vt = Counter()
    for v in df["violation_type"]:
        for item in parse_list(v):
            vt[str(item).strip().upper()] += 1
    w("\n### Top violation types (exploded across multi-violation records)")
    for name, c in vt.most_common(12):
        w(f"- {name}: {c:,} ({100*c/n:.1f}% of records)")

    # Vehicle types
    w("\n### Top vehicle types")
    for name, c in Counter(df["vehicle_type"].str.upper()).most_common(10):
        w(f"- {name}: {c:,}")

    # Police stations (enforcement zones)
    w("\n### Top 15 police stations by violations (enforcement load)")
    for name, c in Counter(df["police_station"]).most_common(15):
        w(f"- {name}: {c:,}")

    # Named junctions (excluding 'No Junction')
    w("\n### Top 15 named junctions (excl. 'No Junction')")
    jc = Counter(j for j in df["junction_name"] if j and j.strip().lower() not in ("no junction", "null", ""))
    for name, c in jc.most_common(15):
        w(f"- {name}: {c:,}")

    # Spatial hotspots via coarse lat/long grid (~110-150m cells at 3 dp)
    lat = pd.to_numeric(df["latitude"], errors="coerce")
    lon = pd.to_numeric(df["longitude"], errors="coerce")
    valid = lat.between(12.6, 13.3) & lon.between(77.3, 77.9)
    w(f"\n### Spatial coverage: {valid.sum():,} rows with valid Bengaluru coords ({100*valid.mean():.1f}%)")
    grid = (lat.round(3).astype("string") + "," + lon.round(3).astype("string"))[valid]
    w("Top 12 hotspot grid cells (~110m), lat,lon : count")
    for cell, c in Counter(grid.dropna()).most_common(12):
        w(f"- {cell}: {c:,}")

    # Temporal patterns
    hours = cdt.dt.hour
    dow = cdt.dt.dayofweek
    w("\n### Temporal pattern - violations by hour of day (UTC; +5:30 for IST)")
    hr = hours.value_counts().sort_index()
    w("  " + " ".join(f"{h:02d}h:{hr.get(h,0)}" for h in range(24)))
    w("\n### By day of week (0=Mon..6=Sun)")
    w("  " + " ".join(f"{d}:{int((dow==d).sum())}" for d in range(7)))

    # Repeat offenders / repeat vehicles
    vn = df["vehicle_number"].replace({"NULL": np.nan})
    vc = vn.value_counts()
    repeat = (vc >= 3).sum()
    w(f"\n### Repeat offenders: {repeat:,} vehicle numbers with >=3 violations; max for a single vehicle = {int(vc.max()) if len(vc) else 0}")

    # Resolution / action
    w(f"\n### Data completeness (null/NULL rate %):")
    for col in ["closed_datetime", "action_taken_timestamp", "validation_status", "data_sent_to_scita", "junction_name"]:
        if col in df.columns:
            w(f"- {col}: {null_rate(df[col])}% missing")
    if "validation_status" in df.columns:
        w("\n### validation_status distribution")
        for name, c in Counter(df["validation_status"]).most_common(8):
            w(f"- {name}: {c:,}")
except Exception as e:
    w(f"PS1 ERROR: {type(e).__name__}: {e}")

# ============================ PS2 ===========================================
w("\n\n## PS2 - Event-Driven Congestion (Astram) dataset\n")
try:
    df2 = pd.read_csv(PS2, dtype=str, keep_default_na=False, low_memory=False)
    n2 = len(df2)
    w(f"- **Rows:** {n2:,}  |  **Columns:** {df2.shape[1]}")
    w(f"- **Columns:** {', '.join(df2.columns)}")

    sdt = to_dt(df2["start_datetime"])
    w(f"- **Time span (start):** {sdt.min()}  ->  {sdt.max()}")

    w("\n### event_type")
    for name, c in Counter(df2["event_type"]).most_common():
        w(f"- {name}: {c:,} ({100*c/n2:.1f}%)")
    w("\n### event_cause (top 15)")
    for name, c in Counter(df2["event_cause"]).most_common(15):
        w(f"- {name}: {c:,}")
    w("\n### requires_road_closure")
    for name, c in Counter(df2["requires_road_closure"]).most_common():
        w(f"- {name}: {c:,}")
    w("\n### priority")
    for name, c in Counter(df2["priority"]).most_common():
        w(f"- {name}: {c:,}")
    w("\n### status")
    for name, c in Counter(df2["status"]).most_common():
        w(f"- {name}: {c:,}")

    # The critical label-gap check: is there ANY response/manpower/barricade field?
    w("\n### LABEL-GAP CHECK (null rates of 'response' fields)")
    for col in ["assigned_to_police_id", "comment", "meta_data", "map_file", "route_path",
                "resolved_at_address", "resolved_datetime", "closed_datetime", "end_datetime"]:
        if col in df2.columns:
            w(f"- {col}: {null_rate(df2[col])}% missing")
    has_manpower = any("manpower" in c.lower() or "barricad" in c.lower() or "diversion" in c.lower()
                       or "staff" in c.lower() or "officer_count" in c.lower() for c in df2.columns)
    w(f"- Any explicit manpower/barricade/diversion column present? **{has_manpower}**")

    # Event duration where both start & end exist
    edt = to_dt(df2["end_datetime"])
    dur = (edt - sdt).dt.total_seconds() / 3600.0
    dur_ok = dur.dropna()
    dur_ok = dur_ok[(dur_ok >= 0) & (dur_ok < 24*30)]
    if len(dur_ok):
        w(f"\n### Event duration (hrs) where end_datetime present (n={len(dur_ok):,}): "
          f"median={dur_ok.median():.1f}, mean={dur_ok.mean():.1f}, p90={dur_ok.quantile(0.9):.1f}")
    else:
        w("\n### Event duration: end_datetime mostly missing -> duration not directly computable")
except Exception as e:
    w(f"PS2 ERROR: {type(e).__name__}: {e}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"\n[written] {OUT}")
